server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  profiles:
    active: local

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: v1
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: v2