spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev1
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev2
server:
  port: 8082
---
server:
  servlet:
    context-path: /api/v1/